version: "2.1"
# Example of spinning 3 nodejs containers
services:
# Example of spinning 3 nodejs containers
services:
  webserver1:
    restart: always
    image: thinegan/debian-nginx
    container_name: nginx1
    hostname: nginxserver1
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/www/public_html/dev.timeclone.com:/home/www/public_html/dev.timeclone.com
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/ssl/private:/etc/ssl/private
    links:
      - "app1:phpserver1"
      - "app2:phpserver2"
      - "app3:phpserver3"

  app1:
    restart: always
    image: thinegan/debian-php5
    container_name: phpfpm1
    hostname: phpserver1
    expose:
      - "9000"
    volumes:
      - /home/www/public_html/dev.timeclone.com:/home/www/public_html/dev.timeclone.com

  app2:
    restart: always
    image: thinegan/debian-php5
    container_name: phpfpm2
    hostname: phpserver2
    expose:
      - "9000"
    volumes:
      - /home/www/public_html/dev.timeclone.com:/home/www/public_html/dev.timeclone.com

  app3:
    restart: always
    image: thinegan/debian-php5
    container_name: phpfpm3
    hostname: phpserver3
    expose:
      - "9000"
    volumes:
      - /home/www/public_html/dev.timeclone.com:/home/www/public_html/dev.timeclone.com

