# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
stages:
  - prepare
  - build
  - security
  - test
  - release

steps:
  clone:
    stage: "prepare"
    title: "Cloning repository"
    type: "git-clone"
    repo: "thinegan/debian-nginx"
    revision: "${{CF_BRANCH}}"
    depth: 1
    git: "git-thinegan-cf"

  build:
    stage: "prepare"
    title: "Building Docker image"
    type: "build"
    image_name: "thinegan/debian-nginx"
    working_directory: "${{clone}}/docker"
    dockerfile: Dockerfile
    disable_push: true

  FetchSnykSecrets:
    stage: "prepare"
    title: Fetch secrets from AWS Secrets Manager
    type: aws-secrets-manager:1.0.1
    arguments:
      AWS_ACCESS_KEY_ID: '${{AWS_ACCESS_KEY_ID}}'
      AWS_SECRET_ACCESS_KEY: '${{AWS_SECRET_ACCESS_KEY}}'
      AWS_DEFAULT_REGION: '${{AWS_DEFAULT_REGION}}'
      secrets:
        - secret_arn: '${{SNYK_STAG_SECRET_ARN}}'
          key: SNYK_ORG_NAME
          store_in: SNYK_ORG_NAME_ARN
        - secret_arn: '${{SNYK_STAG_SECRET_ARN}}'
          key: SNYK_AUTH_TOKEN
          store_in: SNYK_AUTH_TOKEN_ARN

  # push:
  #   stage: "prepare"
  #   title: "Pushing Docker image to Docker hub"
  #   type: push
  #   image_name: "thinegan/debian-nginx"
  #   tag: "mainline-bullseye"
  #   registry: mydockerhub1
  #   candidate: ${{build}}

# Debug mode 4
